[env:esp32s3dev]
platform = espressif32
board = adafruit_feather_esp32s3_reversetft
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
board_build.embed_txtfiles = src/dashboard.html
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    '-DWIFI_PASS="${sysenv.WIFI_PASS}"'
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
